### ISSUE TITLE
sagas/index.js effect creators defined but not respond to the action

### ISSUE THREAD

**Issue by mpowerdevv** [harmony-framework/harmony-boilerplate#70]
**Steps to produce:**
1. Get harmony-boilerplate 
2. Update package.json deps like:

```
...
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
     "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-saga": "^1.1.3",
    "reduxsauce": "^1.1.2",
...
```

3. Run app

**Expected result:**

Following effects are being called when corresponding actions issued. Defined in sagas/index.js:

`
export default function* () {
	yield [
		takeLatest(UsersTypes.LOGIN, sagasUser.login, innorlate),
		takeLatest(UsersTypes.CREATE_USER, sagasUser.createUser, innorlate),
		takeLatest(PostsTypes.FETCH_POSTS, sagasPosts.fetchPosts, innorlate),
		takeLatest(PostsTypes.FETCH_POST, sagasPosts.fetchPost, innorlate),
		takeLatest(PostsTypes.CREATE_POST, sagasPosts.createPost, innorlate),
		takeLatest(PostsTypes.DELETE_POST, sagasPosts.deletePost, innorlate)
	];
}
`
**Actual result:**

1. Effects are NOT being called w/o any error/warning

**The root cause of the problem:**

1. Since redux-saga  v0.15.0 effect _all_ must be used (see [here](https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0))

**How to fix:**

Rewrite in by adding _all(<effects>)_  into sagas/index.js:

`
export default function* () {
	yield all([
		takeLatest(UsersTypes.LOGIN, sagasUser.login, innorlate),
		takeLatest(UsersTypes.CREATE_USER, sagasUser.createUser, innorlate),
		takeLatest(PostsTypes.FETCH_POSTS, sagasPosts.fetchPosts, innorlate),
		takeLatest(PostsTypes.FETCH_POST, sagasPosts.fetchPost, innorlate),
		takeLatest(PostsTypes.CREATE_POST, sagasPosts.createPost, innorlate),
		takeLatest(PostsTypes.DELETE_POST, sagasPosts.deletePost, innorlate)
	]);
}
`

NOTE: don't forget about brackets around effects arrays  _all(<effects>)_

**Comment by refaelok** [comment]
New version are not use to defined sagas in the old way anymore.
Thanks for reporting.

closed.
